// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: flutter pub run build_runner build
// ignore_for_file: type=lint

part of 'claim_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ClaimModel _$ClaimModelFromJson(Map<String, dynamic> json) => ClaimModel(
      id: json['id'] as String,
      claimNumber: json['claimNumber'] as String,
      status: json['status'] as String,
      claimedAmount: (json['claimedAmount'] as num).toDouble(),
      approvedAmount: (json['approvedAmount'] as num?)?.toDouble(),
      serviceDate: json['serviceDate'] as String?,
      submittedAt: json['submittedAt'] as String?,
      reviewedAt: json['reviewedAt'] as String?,
      facilityName: json['facilityName'] as String?,
      householdCode: json['householdCode'] as String?,
      beneficiaryName: json['beneficiaryName'] as String?,
      decisionNote: json['decisionNote'] as String?,
    );

Map<String, dynamic> _$ClaimModelToJson(ClaimModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'claimNumber': instance.claimNumber,
      'status': instance.status,
      'claimedAmount': instance.claimedAmount,
      'approvedAmount': instance.approvedAmount,
      'serviceDate': instance.serviceDate,
      'submittedAt': instance.submittedAt,
      'reviewedAt': instance.reviewedAt,
      'facilityName': instance.facilityName,
      'householdCode': instance.householdCode,
      'beneficiaryName': instance.beneficiaryName,
      'decisionNote': instance.decisionNote,
    };
