// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: flutter pub run build_runner build
// ignore_for_file: type=lint

part of 'coverage_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CoverageModel _$CoverageModelFromJson(Map<String, dynamic> json) =>
    CoverageModel(
      coverageNumber: json['coverageNumber'] as String,
      status: json['status'] as String,
      startDate: json['startDate'] as String?,
      endDate: json['endDate'] as String?,
      nextRenewalDate: json['nextRenewalDate'] as String?,
      premiumAmount: json['premiumAmount'] as String?,
      paidAmount: json['paidAmount'] as String?,
    );

Map<String, dynamic> _$CoverageModelToJson(CoverageModel instance) =>
    <String, dynamic>{
      'coverageNumber': instance.coverageNumber,
      'status': instance.status,
      'startDate': instance.startDate,
      'endDate': instance.endDate,
      'nextRenewalDate': instance.nextRenewalDate,
      'premiumAmount': instance.premiumAmount,
      'paidAmount': instance.paidAmount,
    };
