// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: flutter pub run build_runner build
// ignore_for_file: type=lint

part of 'payment_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PaymentModel _$PaymentModelFromJson(Map<String, dynamic> json) => PaymentModel(
      id: json['id'] as String,
      amount: json['amount'] as String,
      method: json['method'] as String,
      status: json['status'] as String,
      providerName: json['providerName'] as String?,
      receiptNumber: json['receiptNumber'] as String?,
      paidAt: json['paidAt'] as String?,
      createdAt: json['createdAt'] as String?,
    );

Map<String, dynamic> _$PaymentModelToJson(PaymentModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'amount': instance.amount,
      'method': instance.method,
      'status': instance.status,
      'providerName': instance.providerName,
      'receiptNumber': instance.receiptNumber,
      'paidAt': instance.paidAt,
      'createdAt': instance.createdAt,
    };
